### PR TITLE
Added LearnModules to Nextjs

### LINKED ISSUE #837: Learning Modules --> NextJS
Previously, in our old version of DLP (in the vanilla reactjs app version), we had a way to navigate to learning modules. However, when I click on the profile picture in the top right hand corner and navigate to learning modules, I'm not able to see the learning modules page. We should add this page as a route in the nextjs version of DLP. 

You can refer to the `LearnMod` code under `components_old/` directory for the original version of learning modules

rev

### PR DESCRIPTION
**Pull request by Dashrekker**
Added LearnModules to NextJs. The previous exercise implementation doesn't exercise anymore, so I just used trainspace.
image
image
image

### CODE REVIEW

**Comment by karkir0003** [comment]
u can mark pr as ready for review when you are ready? @Dashrekker

**Comment by karkir0003** [comment]
did u test this @Dashrekker

**Comment by Dashrekker** [comment]
@karkir0003 It works with the exception of user progress, which I don't think has been implemented yet.

**Comment by karkir0003** [comment]
hmm. i see. we are thinking of revamping learning modules to be more project oriented. talk to daniel, surya, faris for more detail

**Comment by farisdurrani** [comment]
lgtm, fix the conflicts and await for either Karthik or Daniel's green light before you merge. It would be helpful to add a screen recording but that's not necessary

**Review by farisdurrani — APPROVED** [review]

**Comment by karkir0003** [comment]
@farisdurrani i think we need to rethink the whole learning modules design

**Comment by farisdurrani** [comment]
Agree @karkir0003 but I think this PR is still worthwhile to merge in. It has some components we'll need for the project-oriented version, especially the trainspace exercise, and it gives an initial framework for the next developers to work on

**Comment by karkir0003** [comment]
ok. agreed @farisdurrani

**Comment by karkir0003** [comment]
merge when youre ready

**Comment by farisdurrani** [comment]
Thanks Karthik, @Dashrekker please fix the conflicts and then proceed with merging

**Comment by farisdurrani** [comment]
You can press merge now @Dashrekker . Thanks!

**Pull request merged**
