### PR TITLE
removed webdriver file

### LINKED ISSUE #828: Remove Selenium Webdriver Script
**Problem:** I was initially thinking of implementing an endpoint with Selenium webdriver in order to open up a user's onnx file from a training execution. However, I didn't really prioritize it due to other important tasks. Now, `backend/webdriver.py` is unused code that's been living in our repo. Also, from my memory, `backend/webdriver.py` doesn't really get called anywhere else in the backend.

**Solution:** Reduce tech debt by removing `backend/webdriver.py` file

**Time required:** 10 minutes of your time. 

**Branch Setup**
```
git checkout nextjs
git pull origin nextjs
git checkout -b remove-webdriver
```

If the above commands don't work, run `git stash` before running the above sequence of commands

### PR DESCRIPTION
**Pull request by AmyCGT**
removed unused backend/webdriver.py script

### CODE REVIEW

**Comment by karkir0003** [comment]
can you remove `selenium` from `conda/environment.yml` @AmyCGT

**Comment by AmyCGT** [comment]
selenium is not in environment.yml, i have removed it from requirements.txt tho

**Comment by karkir0003** [comment]
> selenium is not in environment.yml, i have removed it from requirements.txt tho

thank you!

**Comment by karkir0003** [comment]
> selenium is not in environment.yml, i have removed it from requirements.txt tho

can you update the PR accordingly? @AmyCGT

**Comment by karkir0003** [comment]
make sure you update this branch with latest version of nextjs @AmyCGT

**Review by karkir0003 — APPROVED** [review]

**Pull request merged**
