### PR TITLE
Add QuickTrainSpace dashboard banner and update refresh button color

### LINKED ISSUE #841: [FEATURE]: Quick TrainSpace Banner and Refresh Button UI Changes
### Feature Name

Add "QuickTrainSpace" dashboard banner for convenient access to training models. Also changed refresh button color to blue since red color seemed out of place

### Your Name

Surya Subramanian

### Description

The "QuickTrainSpace" feature needs to be implemented on the dashboard of our application. This feature aims to provide general users with a convenient and efficient way to train their model.

### PR DESCRIPTION
**Pull request by codingwithsurya**
# Implement QuickTrainSpace feature and update refresh button color

**What user problem are we solving?**
This pull request addresses the need for a convenient and efficient way for general users to access and train their models on the dashboard. It also improves the visual consistency by changing the refresh button color.

**What solution does this PR provide?**
The PR implements the "QuickTrainSpace" feature on the dashboard, allowing general users to easily access and train their models. Additionally, it updates the refresh button color from red to blue, ensuring better visual consistency within the application.

**Testing Methodology**
To ensure the changes made in this pull request do not break existing functionality, the following testing methodology was followed:
1. Manually tested the new "QuickTrainSpace" feature on the dashboard to verify its functionality, including accessing and training models.
2. Tested the updated refresh button color to ensure it displays as intended and maintains visual consistency across different browsers and devices.

**Any other considerations**

### CODE REVIEW

**Comment by karkir0003** [comment]
user problem description not specific to this pr @yeaitsurya

**Comment by karkir0003** [comment]
user problem description not specific to this pr @yeaitsurya

**Comment by karkir0003** [comment]
looks good to me. @farisdurrani @dwu359 thoughts?

**Comment by dwu359** [comment]
Screenshot?

**Comment by codingwithsurya** [comment]
> Screenshot?

in dlp/frontend discord channel

**Comment by karkir0003** [comment]
@yeaitsurya plz attach screenshot in pr as well for tracking purposes

**Comment by codingwithsurya** [comment]
> @yeaitsurya plz attach screenshot in pr as well for tracking purposes

image

**Comment by karkir0003** [comment]
@dwu359

**Review by karkir0003 — CHANGES_REQUESTED** [review]
problem:
the banner you created only gets rendered when a user has no trainspaces at all to display. @yeaitsurya

**Comment by codingwithsurya** [comment]
@karkir0003 should we just close this pull request?

**Comment by karkir0003** [comment]
> @karkir0003 should we just close this pull request?

yes for now

**Pull request closed without merging**
