### PR TITLE
tmux script updated to use dlp-cli

### LINKED ISSUE #1081: [FEATURE]: Tmux Script Update
### Feature Name

Update Tmux Script to use DLP CLI

### Your Name

Karthik Subramanian

### Description

We should update `tmux-script.sh` to use `dlp-cli` to spin up the frontend and backend. We start frontend through running `dlp-cli frontend start` at `~/Deep-Learning-Playground` directory. We start backend through running `dlp-cli backend start` at `~/Deep-Learning-Playground` directory

Point of contact for Code Review: Noah Iversen (@noah-iversen)
Benefits of this fix:
* `tmux-script.sh` relies on `dlp-cli`, which abstracts the starting of frontend and backend (ie: if the package manager were to change for frontend or backend, we update the respective `dlp-cli` command, leaving the `tmux-script.sh` unaffected

### PR DESCRIPTION
**Pull request by yebyyy**
# Feature 1081

Github Issue Number Here: #1081
**tmux updated to use dlp-cli**

**modifying backend and frontend start code**

**runnning brew tmux install and ./tmux-script.sh**
> How did you test your changes and verify that existing functionality is not broken

**Any other considerations**

### CODE REVIEW

**Review by farisdurrani — APPROVED** [review]

**Comment by farisdurrani** [comment]
Lgtm

**Comment by noah-iversen** [comment]
Looks good, we still have to keep in mind this tmux script does not work in WSL currently. Still on our TODOs to iron out that issue.

**Comment by karkir0003** [comment]
> Looks good, we still have to keep in mind this tmux script does not work in WSL currently. Still on our TODOs to iron out that issue.

Got it @noah-iversen. I was able to run `tmux-script.sh` on windows, but through using Ubuntu terminal on windows

**Comment by karkir0003** [comment]
> Looks good, we still have to keep in mind this tmux script does not work in WSL currently. Still on our TODOs to iron out that issue.

@Keon-San have u tried running tmux -script.sh in wsl?

**Comment by karkir0003** [comment]
@farisdurrani @yebyyy, @Keon-San tested this PR out and it works on WSL from my understanding. 

@Keon-San can you confirm?

**Comment by farisdurrani** [comment]
@Keon-San can you please fix the conflicts so we can proceed to merging?

**Comment by farisdurrani** [comment]
Works on Mac, feel free to merge

**Pull request merged**
