### PR TITLE
New POST endpoint to create Trainspace, as well as new dynamodb table

### PR DESCRIPTION
**Pull request by ssh51117**
New POST endpoint to create Trainspace, as well as new dynamodb table

Github Issue Number Here: #1073
**Issue Description**
Old POST endpoints went to a dynamodb table in us-west-2, and were separated by whether they were image or tabular. They also did not contain the right information

**What solution does this PR provide?**
Made new create_trainspace file with the correct information, which can take in a list of models, datasets, and blocks and post them to a new trainspace database in us-east-1, and modified the necessary files for this to function correctly.
Files changed:
.gitignore: added terraform.tfstate
dynamodb.tf: changed region to us-east-1 and updated file to reflect new dynamo table
create_trainspace.ts: wrote this file to create the new POST endpoint
get_all_trainspace.ts: changed function to get data from the correct table
serverless/sst.config.ts: updated region to us-east-1
serverless/stacks/AppStack.ts: added POST trainspace/create function

**Testing Methodology**
Tested using Postman to POST data to the new dynamodb table successfully. Test using multiple blocks and multiple datasets in one entry.

**Any other considerations**
create_trainspace.ts can be easily edited to take different parameters if need be.

### CODE REVIEW

**Comment by farisdurrani** [comment]
We don't push *.tfstate files [ref](https://github.com/github/gitignore/blob/main/Terraform.gitignore). Please remove the file

**Comment by ssh51117** [comment]
> We don't push *.tfstate files [ref](https://github.com/github/gitignore/blob/main/Terraform.gitignore). Please remove the file

I added dlp-terraform/dynamodb/terraform.tfstate to the gitignore. Is there anything else I need to do?

**Comment by farisdurrani** [comment]
You'll need to explicitly delete the file and push that change for it to disappear from the repo @ssh51117

**Comment by ssh51117** [comment]
got it. Should I leave the file in gitignore? @farisdurrani

**Comment by farisdurrani** [comment]
Yes

**Comment by farisdurrani** [comment]
So... SonarCloud is complaining about duplicate code in `create_trainspace.ts` and `create_tabular_trainspace.ts` starting from `if (putCommandInput == null)`. Personally, I don't have a problem with this since we may want each file to act differently in the future, so I'll give my approval. But do wait for at least one other reviewer

**Review by farisdurrani — APPROVED** [review]

**Comment by karkir0003** [comment]
@farisdurrani @ssh51117 lets not worry abt sonarcloud here

**Pull request merged**
