### PR TITLE
converted rest of the non-training files to tsx

### PR DESCRIPTION
**Pull request by dwu359**
Part of overall conversion to ts

### CODE REVIEW

**Review by karkir0003 — COMMENTED** [review]
did u test this out end to end? keep in mind login seems to not be working? @dwu359

**Comment by dwu359** [comment]
I've tested everything except file url uploading (idk a good url to test with), everything else seems to work fine

**Comment by farisdurrani** [comment]
@dwu359 Try this URL I got from Googling iris csv: https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv

**Review by farisdurrani — APPROVED** [review]

**Comment by karkir0003** [comment]
@dwu359 did you try testing out upload url from faris's comment

**Comment by dwu359** [comment]
Yes it works

**Pull request merged**
