### PR TITLE
Pnpm

### PR DESCRIPTION
**Pull request by dwu359**
# pnpm

**What solution does this PR provide?**

Switches package management from yarn to pnpm for frontend and serverless.

Also modified the dlp-cli so that it uses pnpm instead of yarn. Also add a --yarn flag in case if anyone is in the process of transitioning from yarn to pnpm.

Also modified node build check workflow to use pnpm instead of yarn.

**Testing Methodology**
Everything was able to be installed via pnpm.

**Any other considerations**
https://github.com/DSGT-DLP/dlp-cli/pull/11

### CODE REVIEW

**Comment by karkir0003** [comment]
@dwu359 can you add an explanation in the github issue (or pr) for why we want to use pnpm over yarn? have we ensured that pnpm can still install any node dependency we want to use in the future (at least for 90+% of our potential  usecases).

**Review by karkir0003 — CHANGES_REQUESTED** [review]
address my comment @dwu359

**Comment by dwu359** [comment]
> @dwu359 can you add an explanation in the github issue (or pr) for why we want to use pnpm over yarn? have we ensured that pnpm can still install any node dependency we want to use in the future (at least for 90+% of our potential usecases).

From what I've read, pnpm is slightly faster than yarn berry and uses up less space than yarn because it utilizes symlinks instead of directly copying packages. That did seem the case for my machine, but I'll need other ppl to try it out also if that is the case. Pnpm was able to install basically anything that I threw at it, since it installs from the npm registry.

**Comment by dwu359** [comment]
Actually if you look at the build times for https://github.com/DSGT-DLP/Deep-Learning-Playground/actions/workflows/node.js.yml, it does seem to be about 20s faster

**Comment by farisdurrani** [comment]
Works on my laptop

**Review by farisdurrani — APPROVED** [review]

**Review by karkir0003 — APPROVED** [review]

**Pull request merged**
