### PR TITLE
Fixing img_model_error

### PR DESCRIPTION
**Pull request by hassannaveed1997**
Fixing a problem with img model parsing

**What user problem are we solving?**
Removes the extra quotation mark for parameters in the image model

### CODE REVIEW

**Review by karkir0003 — COMMENTED** [review]
test that tabular run and img run work locally? @hassannaveed1997

**Comment by karkir0003** [comment]
@farisdurrani for visibility

**Comment by hassannaveed1997** [comment]
> test that tabular run and img run work locally? @hassannaveed1997

Just tested img, tabular and ml for the IRIS dataset. Worked for all three so it should be fine. Only thing is if in the future some DL model has string parameters then a more sophisticated fix would be needed (probably on the frontend side).

**Comment by karkir0003** [comment]
can u jot as github issue? @hassannaveed1997

**Review by karkir0003 — APPROVED** [review]
@farisdurrani for visibility

**Review by farisdurrani — APPROVED** [review]

**Comment by farisdurrani** [comment]
Looks good, feel free to merge this in @hassannaveed1997

**Pull request merged**
