### PR TITLE
Train Results UI

### PR DESCRIPTION
**Pull request by dwu359**
# Train Results UI

**What user problem are we solving?**
Added some charts and graphs for the train results UI. Right now it only displays mocked data, but I plan on doing the rest of this task in a 2nd PR after the train microservice is set up.

**What solution does this PR provide?**

**Testing Methodology**
How did you test your changes and verify that existing 
functionality is not broken

**Any other considerations**

### CODE REVIEW

**Comment by karkir0003** [comment]
@dwu359 screenshot of ui?

**Comment by dwu359** [comment]
> @dwu359 screenshot of ui?

image

**Review by karkir0003 — APPROVED** [review]

**Comment by karkir0003** [comment]
and the routing works?

**Comment by karkir0003** [comment]
like from train button click, u get routed tk this page. also, can we access results page from dashboard or that db logic isnt yet implemented? @dwu359

**Comment by dwu359** [comment]
Yes the routing works at least on my end. The results page cannot be accessed from the dashboard yet, but I'm sure that that shouldn't be too hard once the training microservice is set up.

**Comment by karkir0003** [comment]
ok

**Comment by karkir0003** [comment]
u are safe to merge @dwu359 approved on my end

**Pull request merged**
