### PR TITLE
remove old components + mock store files

### LINKED ISSUE #858: Remove the components_old directory
**Problem:** As we have worked on upgrading our frontend to NextJS, we kept the old components under `components_old/` directory. However, now that we have most of the major files in NextJS, we can remove the `components_old/` directory.

**Solution:** Delete `components_old/` directory and any css files related to old version of DLP

### PR DESCRIPTION
**Pull request by karkir0003**
**What user problem are we solving?**
Currently, build checks are failing because the components_old/ directory is not in use. that causes delay and confusion on the PR build checks.
**What solution does this PR provide?**
Remove old components and files now that most of the repo is upgraded to NextJS
**Testing Methodology**
spin up the app in localhost + existing build checks

**Any other considerations**
make sure we thoroughly cleaned up old files that we don't use from the old setup

### CODE REVIEW

**Review by farisdurrani — APPROVED** [review]

**Comment by farisdurrani** [comment]
Approved. I see some files which are not part of components_old/. If this is not intentional, please fix but I think they are safe to delete

**Comment by karkir0003** [comment]
> Approved. I see some files which are not part of components_old/. If this is not intentional, please fix but I think they are safe to

which files? @farisdurrani

**Comment by farisdurrani** [comment]
image

**Comment by farisdurrani** [comment]
mockStore and trainModel, as in the picture attached

**Pull request merged**
