### PR TITLE
Feature 1123 Added Trainspace, Model, User Tables to Terraform Infra

### PR DESCRIPTION
**Pull request by MugPand**
# DynamoDB & Terraform Update

Github Issue Number Here: GitHub #1123
**What user problem are we solving?**
The current DynamoDB tables and Terraform script reflect an older version of infra-configurations. 

**What solution does this PR provide?**
Updated DynamoDB tables and Terraform script to reflect new changes proposed by the following diagram: **Also added user_id as GSI to ModelTable**.
image

**Testing Methodology**
> How did you test your changes and verify that existing functionality is not broken
Ran terraform file configurations and validated created DynamoDB Tables on AWS.

**Any other considerations**

### CODE REVIEW

**Comment by farisdurrani** [comment]
This isn't mandatory but do try applying the tf plan and then destroy the built resources to make sure the .tf file works.

```
terraform init
terraform fmt
terraform plan
terraform apply
terraform destroy
```

It may not work if you don't have the proper access. I'll approve this after 24 hours to see if anyone else has any comments

**Comment by MugPand** [comment]
> This isn't mandatory but do try applying the tf plan and then destroy the built resources to make sure the .tf file works.
> 
> ```
> terraform init
> terraform fmt
> terraform plan
> terraform apply
> terraform destroy
> ```
> 
> It may not work if you don't have the proper access. I'll approve this after 24 hours to see if anyone else has any comments

@karkir0003 and I just tested that successfully.

**Comment by karkir0003** [comment]
> This isn't mandatory but do try applying the tf plan and then destroy the built resources to make sure the .tf file works.
> 
> ```
> terraform init
> terraform fmt
> terraform plan
> terraform apply
> terraform destroy
> ```
> 
> It may not work if you don't have the proper access. I'll approve this after 24 hours to see if anyone else has any comments

can we make this a best practice for tf related stuff?? can it be automated

**Comment by farisdurrani** [comment]
Yes, this should be best practice. Can it be automated? Yes, but I won't recommend it. If it fails, there may be AWS resources that will never get destroyed (more cost)

**Review by farisdurrani — APPROVED** [review]

**Comment by farisdurrani** [comment]
Feel free to merge @MugPand

**Pull request merged**
