### PR TITLE
Adding Audio Routing

### LINKED ISSUE #1162: [FEATURE]: Create Audio Route for Deep Learning Playground and Implement Audio Routing in urls.py
### Feature Name

In order to extend the Deep Learning Playground's functionality to support audio data processing, we need to create an Audio Route consisting of `schemas.py`, `audio.py`, and `init.py`. This route will enable users to interact with audio data, upload audio files, and train deep learning models specifically designed for audio tasks. Also use  `urls.py` file for routing requests to the `audio.py` file. 

### Your Name

Surya Subramanian

### Description

As part of our ongoing efforts to expand the capabilities of our deep learning playground, we need to create a new route for audio processing. This route should be similar to the existing image and tabular routes - use these for inspiration!

The new route should be located under the routes directory and should be named audio. Inside this directory, we need to create three files: `schemas.py`, `audio.py`, and `__init__.py`.

The next step is to integrate this route into our main application.

The task is to add the audio route to the `urls.py` file. This will allow the application to route requests to the appropriate handlers in the `audio.py `file.

Please ensure that the audio route is correctly integrated and that all tests pass after the integration.

Let me know if you need any additional information or clarification.

### PR DESCRIPTION
**Pull request by codingwithsurya**
# Adding Audio Routing

Github Issue Number Here: <#1162>
**What user problem are we solving?**
We are extending the Deep Learning Playground's capabilities to include audio data processing, allowing users to interact with, upload, and train deep learning models on audio files.

**What solution does this PR provide?**
This PR introduces a new route for audio processing similar to the existing image and tabular data routes. It includes the creation of schemas.py, audio.py, and __init__.py under the routes/audio directory. Additionally, it integrates this new route into the main application via urls.py.

**Testing Methodology**
> How did you test your changes and verify that existing functionality is not broken

**Any other considerations**

### CODE REVIEW

**Comment by karkir0003** [comment]
@codingwithsurya how did you test that this PR works?

**Comment by karkir0003** [comment]
What are the next steps after this PR?

**Review by karkir0003 — COMMENTED** [review]
left comments. please address

**Comment by codingwithsurya** [comment]
> @codingwithsurya how did you test that this PR works?

i didn't run any unit tests or anything since this was just getting the folder and routing setup

**Comment by codingwithsurya** [comment]
> What are the next steps after this PR?

just filling out the files with necessary things for audio training. check out issues #1161 and #1156 for greater detail

**Comment by codingwithsurya** [comment]
@karkir0003 i can only go ahead and get the schemas.py set up in this pr itself if u would like

**Comment by karkir0003** [comment]
> @karkir0003 i can only go ahead and get the schemas.py set up in this pr itself if u would like 

sounds good

**Comment by codingwithsurya** [comment]
> > @karkir0003 i can only go ahead and get the schemas.py set up in this pr itself if u would like
> 
> sounds good

let me do some research on how this will look like. we're employing kind of a different strategy here with our custom architecture. i'll get back to u on this.

**Comment by codingwithsurya** [comment]
schemas.py will be handled in #1156.

**Review by karkir0003 — APPROVED** [review]

**Pull request merged**
