### PR TITLE
Tmux poetry update

### PR DESCRIPTION
**Pull request by noah-iversen**
Tmux poetry update

**What user problem are we solving?**

We're restoring tmux script functionality with poetry.

**What solution does this PR provide?**

I simply made changes to file with updated commands.

**Testing Methodology**
How did you test your changes and verify that existing 
functionality is not broken

I pulled latest version of nextjs and script worked fine with no errors.

**Any other considerations**

### CODE REVIEW

**Comment by karkir0003** [comment]
@noah-iversen screenshot of output when you run the tmux script? I have Ubuntu distro, so will it work there?

**Review by karkir0003 — CHANGES_REQUESTED** [review]
looks good to me, but please followup with my global comment in the PR @noah-iversen

**Review by farisdurrani — APPROVED** [review]

**Comment by noah-iversen** [comment]
> @noah-iversen screenshot of output when you run the tmux script? I have Ubuntu distro, so will it work there?

Here ya go.

Screenshot 2023-09-02 143435

Screenshot 2023-09-02 143500

**Comment by karkir0003** [comment]
fantastic @noah-iversen . can you go into localhost:3000 and log into dlp. send screenshot of the backend logs?

**Comment by noah-iversen** [comment]
> fantastic @noah-iversen . can you go into localhost:3000 and log into dlp. send screenshot of the backend logs?

frontend output tmux
Backend output tmux
dlp page

**Comment by karkir0003** [comment]
good job. safe to merge

**Review by karkir0003 — APPROVED** [review]

**Pull request merged**
