### PR TITLE
Train tsx

### PR DESCRIPTION
**Pull request by dwu359**
Part of overall conversion to ts

### CODE REVIEW

**Comment by dwu359** [comment]
I tested basic tabular, image-models, and classical-ml, but not object detection or invalid inputs

**Comment by karkir0003** [comment]
lets try testing obj detection? @dwu359

**Comment by karkir0003** [comment]
@farisdurrani can you review

**Comment by karkir0003** [comment]
@dwu359 fix the build checks

**Comment by dwu359** [comment]
object-detection works now

**Comment by farisdurrani** [comment]
A few console logs and need to specify the type of `choice` more than a string. Gimme a moment

**Comment by farisdurrani** [comment]
This is very good work @dwu359 . Love it!

**Review by farisdurrani — APPROVED** [review]

**Pull request merged**
