### PR TITLE
Converting AWS ECS resources to Terraform

### PR DESCRIPTION
**Pull request by thomaschin35**
Converting AWS ECS resources to Terraform

**What user problem are we solving?**
We are making sure that our AWS Resources are backed up through Terraform.

**What solution does this PR provide?**
Allows us to redeploy the resource easily 

**Testing Methodology**
Tested by deploying resources into AWS and checking configurations with actual resource

Screen Shot 2023-04-25 at 12 12 51 AM
Screen Shot 2023-04-25 at 12 13 48 AM
Screen Shot 2023-04-25 at 12 13 56 AM

### CODE REVIEW

**Comment by farisdurrani** [comment]
The TF code looks good, I'd approve it but I have less experience in this compared to @karkir0003

**Comment by karkir0003** [comment]
did u test it out @thomaschin35

**Comment by thomaschin35** [comment]
> 

Yes it has been tested

**Comment by karkir0003** [comment]
plz delete the excess test train service on ecs? @thomaschin35 

did you do a real deploy tho? if not do that before merging this pr in

**Review by karkir0003 — APPROVED** [review]

**Review by karkir0003 — CHANGES_REQUESTED** [review]
pr into nextjs branch? @farisdurrani can u confirm

**Comment by thomaschin35** [comment]
I did a real deploy and I deleted the test services and test clusters already. I checked using the test clusters and services first, but I didn't completely replace the one we have, cause right now it has all the right settings. I can replace the cluster and service that we have right now if that's what you are asking.

**Comment by karkir0003** [comment]
> I did a real deploy and I deleted the test services and test clusters already. I checked using the test clusters and services first, but I didn't completely replace the one we have, cause right now it has all the right settings. I can replace the cluster and service that we have right now if that's what you are asking.

that's what i was asking @thomaschin35. if the test version of training container works, you can do a real deploy. currently, the app is not in beta testing phase

**Review by farisdurrani — APPROVED** [review]

**Review by karkir0003 — APPROVED** [review]

**Pull request merged**
