### PR TITLE
Learning modules

### PR DESCRIPTION
**Pull request by Sebiancoder**
#Added exercise functionality to learning modules

**This PR allows users to create models while working through the learning modules, thus immediately being able to test out the concepts they have learned**

**Code and functionality was adapted from training page.**

**Testing Methodology**
Code was tested by trying to train a variety of modules with various users through the learning modules page. 

[Link to video demonstration](https://drive.google.com/file/d/1tI1ArFqNsatBzKrjN5fVTdtmuCL2mfUd/view?usp=sharing)

### CODE REVIEW

**Comment by karkir0003** [comment]
@Sebiancoder very impressed.

BIG action item: please pull latest version of dev and upgrade files in learning modules to typescript. lets have this ready on your end before merging

**Review by karkir0003 — CHANGES_REQUESTED** [review]
upgrade learn modules files to typescript

**Comment by farisdurrani** [comment]
Approved after all checks passed

**Review by farisdurrani — APPROVED** [review]

**Review by karkir0003 — APPROVED** [review]

**Comment by farisdurrani** [comment]
@Sebiancoder please test this out one more time and merge your changes

**Pull request merged**
