### PR TITLE
User object passed in to backend

### LINKED ISSUE #584: Reorganization on arguments passing to the backend
**Describe the solution you'd like**
As the complexity of our app grows, the number of arguments being passed to the backend gets more. The many things being passed make it hard to debug the app. We propose to nest and order the arguments passed from a flat hierarchy to a more tapered hierarchy, e.g. combining the user's email and password into one `user` Javascript object to be passed into the POST body. 

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b modal-name
```
FYI: If you are not able to immediately run `git checkout dev`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

### PR DESCRIPTION
**Pull request by farisdurrani**
# User object passed in to backend 

**What user problem are we solving?**
- Irregularity in passing in user's info to backend attempting to fix #584 

**What solution does this PR provide?**
- Instead of passing in the user's uid as a single argument, we pass in an object to the backend with the name, email, and uid of the user
- CODEOWNERS update to only include @farisdurrani and @karkir0003 as the only active PR reviewers of this repo

**Testing Methodology**
Tested on tabular on prod and end

**Any other considerations**

### CODE REVIEW

**Comment by farisdurrani** [comment]
@karkir0003 unfortunately revamping how the arguments get passed in to the backend is difficult since we have to take into account how other training models are doing it. I recommend we defer this problem to later to focus on other high-priority tasks

**Comment by farisdurrani** [comment]
The Prettier action is down right now, not because of us. Ignore that for now

**Comment by karkir0003** [comment]
link @farisdurrani

**Comment by karkir0003** [comment]
> @karkir0003 unfortunately revamping how the arguments get passed in to the backend is difficult since we have to take into account how other training models are doing it. I recommend we defer this problem to later to focus on other high-priority tasks

are you sure abt that? could u provide an example? im totally on board punting this to focus on higher priority tasks?

**Comment by karkir0003** [comment]
link @farisdurrani

**Review by karkir0003 — CHANGES_REQUESTED** [review]
deprioritized bc of discussion in comments @farisdurrani

**Comment by karkir0003** [comment]
@farisdurrani do we cloee this pr for now?

**Comment by farisdurrani** [comment]
> > @karkir0003 unfortunately revamping how the arguments get passed in to the backend is difficult since we have to take into account how other training models are doing it. I recommend we defer this problem to later to focus on other high-priority tasks
> 
> are you sure abt that? could u provide an example? im totally on board punting this to focus on higher priority tasks?

Bascially this function:
image

Every training model handles the training parameter handling slightly differently and while I can make it work to Tabular, I'm not sure how to test the other training models, and the problem gets complicated if the backend were to pass in the reqeust.data deep

**Comment by karkir0003** [comment]
so like json depth?

**Comment by farisdurrani** [comment]
The value of this PR is not to fix the reorganization issue but to make the first step: by fixing how we send the user's data and notification settings uniformly. So there is value in approving this PR

**Comment by karkir0003** [comment]
i thought request.data isnt gonna get affected @farisdurrani

**Comment by karkir0003** [comment]
> > > @karkir0003 unfortunately revamping how the arguments get passed in to the backend is difficult since we have to take into account how other training models are doing it. I recommend we defer this problem to later to focus on other high-priority tasks
> > 
> > are you sure abt that? could u provide an example? im totally on board punting this to focus on higher priority tasks?
> 
> Bascially this function:
> image
> 
> Every training model handles the training parameter handling slightly differently and while I can make it work to Tabular, I'm not sure how to test the other training models, and the problem gets complicated if the backend were to pass in the reqeust.data deep

i think u would test similar way in other training routes? @farisdurrani

**Comment by farisdurrani** [comment]
> i thought request.data isnt gonna get affected @farisdurrani

Like how many times the backend uses the HTML body data and how far along it passes that object to other functions

**Comment by farisdurrani** [comment]
> > > > @karkir0003 unfortunately revamping how the arguments get passed in to the backend is difficult since we have to take into account how other training models are doing it. I recommend we defer this problem to later to focus on other high-priority tasks
> > > 
> > > 
> > > are you sure abt that? could u provide an example? im totally on board punting this to focus on higher priority tasks?
> > 
> > 
> > Bascially this function:
> > image
> > Every training model handles the training parameter handling slightly differently and while I can make it work to Tabular, I'm not sure how to test the other training models, and the problem gets complicated if the backend were to pass in the reqeust.data deep
> 
> i think u would test similar way in other training routes? @farisdurrani

I could. I'll need to find out how for the other training models

**Comment by farisdurrani** [comment]
> i thought request.data isnt gonna get affected @farisdurrani

Oh it will. It's the main thing that gets affected if we go this route

**Comment by karkir0003** [comment]
> > i thought request.data isnt gonna get affected @farisdurrani
> 
> Like how many times the backend uses the HTML body data and how far along it passes that object to other functions

i see. so what do you suggest @farisdurrani

**Comment by karkir0003** [comment]
> > > > > @karkir0003 unfortunately revamping how the arguments get passed in to the backend is difficult since we have to take into account how other training models are doing it. I recommend we defer this problem to later to focus on other high-priority tasks
> > > > 
> > > > 
> > > > are you sure abt that? could u provide an example? im totally on board punting this to focus on higher priority tasks?
> > > 
> > > 
> > > Bascially this function:
> > > image
> > > Every training model handles the training parameter handling slightly differently and while I can make it work to Tabular, I'm not sure how to test the other training models, and the problem gets complicated if the backend were to pass in the reqeust.data deep
> > 
> > i think u would test similar way in other training routes? @farisdurrani
> 
> I could. I'll need to find out how for the other training models

so then we can punt this to later in favor of more important tasks?

**Comment by farisdurrani** [comment]
I suggest we make small incremental changes as we make more commits in the future. This will not be solved in one PR but rather a series of PRs, starting with this one that changes how we send user data to the backend. We merge this PR and make changes as we move on later

**Comment by karkir0003** [comment]
hmmm

**Comment by farisdurrani** [comment]
Tested this PR on prod mode, all works

**Review by karkir0003 — APPROVED** [review]

**Pull request merged**
