### PR TITLE
Fix bug #1117

### PR DESCRIPTION
**Pull request by TawhidAhmad**
# Deletion of yarn.lock file 

Github Issue Number Here: <#1117>
**What user problem are we solving?**
Bug with frontend having yarn.lock file

**What solution does this PR provide?**
Delete the yarn.lock file in frontend/

**Testing Methodology**
> How did you test your changes and verify that existing functionality is not broken
Opened the localhost and the page was present. 

**Any other considerations**

### CODE REVIEW

**Comment by farisdurrani** [comment]
Did you try running the frontend to see if it still works? @TawhidAhmad

**Comment by TawhidAhmad** [comment]
Yes, I tried the frontend and it worked. @farisdurrani

**Review by farisdurrani — APPROVED** [review]
Approved. Feel free to merge @TawhidAhmad

**Comment by karkir0003** [comment]
> Yes, I tried the frontend and it worked. @farisdurrani

In the future, could you include a screen recording?

**Pull request merged**
