### PR TITLE
Merge fix-dashboard into dev

### PR DESCRIPTION
**Pull request by dwu359**
# Merge Fix-dashboard into dev

**What user problem are we solving?**
Make the dashboard look more like a dashboard with charts
**What solution does this PR provide?**
Adds a doughnut chart displaying # of trains for each model type, a bar chart displaying training frequency by date, and a refresh spinner since I thought that would be useful when refactoring the code a bit for the charts
**Testing Methodology**
How did you test your changes and verify that existing 
functionality is not broken

Charts display properly
**Any other considerations**

### CODE REVIEW

**Comment by karkir0003** [comment]
@dwu359 screenshot of dashboard

**Review by karkir0003 — CHANGES_REQUESTED** [review]
screenshot of charts in dashboard? did you test that the charts update correctly

@farisdurrani any comments?

**Comment by dwu359** [comment]
> @dwu359 screenshot of dashboard

image

**Comment by dwu359** [comment]
> screenshot of charts in dashboard? did you test that the charts update correctly
> 
> @farisdurrani any comments?

Not sure if I can test if it updates with new executions unless if I go into prod, but the charts do update if I manually change the data

**Comment by farisdurrani** [comment]
The super long code can be aesthetically improved by separating it but for now, I'll just approve this

**Comment by karkir0003** [comment]
can u hover over the plots? @dwu359 is it interactive? are you being consistent with other charts we've constructed out of curiosity

**Comment by karkir0003** [comment]
@dwu359 I don't think a bar chart is the best model for modeling training across time. Look into a line plot? @dwu359

**Comment by karkir0003** [comment]
but this is non-blocking. do in a followup PR?

**Review by karkir0003 — APPROVED** [review]

**Review by farisdurrani — APPROVED** [review]

**Comment by farisdurrani** [comment]
PR approved @dwu359 . But look into those advices for future code. We want package standardization, code aesthetics, and good vis communication

**Comment by dwu359** [comment]
> can u hover over the plots? @dwu359 is it interactive? are you being consistent with other charts we've constructed out of curiosity

It's interactive, I think I implemented it differently than the other charts currently in dlp though (I used Chart.js to implement the charts)

**Pull request merged**
