### PR TITLE
swagger ui api endpoints clean up

### LINKED ISSUE #827: Remove SWAGGER_UI_ROUTES
**Problem:** Previously, we used to use Swagger UI to document our backend API enpdoints. However, Swagger UI was too difficult to use and caused some annoying bugs. Thus, we should remove code relating to Swagger UI. 

**Solution:** DLP shifted to using a tool called Redocly to nicely document our backend API endpoints. The goal for this task is to remove the `SWAGGER_UI_ROUTES` variable in `backend/middleware.py` in order to reduce tech debt and keep overall codebase clean

**Time required:** Should be able to be completed in half a day since you will only need to be modifying one file and cleaning up some small logic. 

**Branch Setup Instructions**
```
git checkout nextjs
git pull origin nextjs
git checkout -b swagger-ui-routes-remove
```

If the above commands don't work, run `git stash` before running the above sequence of commands

### PR DESCRIPTION
**Pull request by AmyCGT**
removed swagger ui usage from middleware

### CODE REVIEW

**Comment by karkir0003** [comment]
@AmyCGT verification steps to test that backend still works? can you login to DLP for example

**Comment by farisdurrani** [comment]
Can you also make sure the exempt paths are exempt i.e. can be accessed publicly?

**Comment by karkir0003** [comment]
> Can you also make sure the exempt paths are exempt i.e. can be accessed publicly?

for example, try localhost:8000/api/test/. you should see a json saying "backend is alive" @AmyCGT

**Comment by AmyCGT** [comment]
test cleared 
image

**Review by karkir0003 — APPROVED** [review]

**Pull request merged**
