### PR TITLE
Remove playground-frontend directory

### LINKED ISSUE #757: Deprecate /playground-frontend directory
**Describe the solution you'd like**
The additional child directory /playground-frontend is unnecessary. This PR seeks to remove that child directory so all frontend files will be stored in /frontend instead, not /frontend/playground-frontend

Anyone currently working on the frontend contents will have to manually move up their frontend files up one directory like so. Do not try git stash and solve the git conflicts on your own as over 300 files will be in conflict. 

https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/40067313/758d7818-a98f-42a0-b129-80cad2e6a536

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b rm-playground-frontend
```
FYI: If you are not able to immediately run `git checkout dev`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

### PR DESCRIPTION
**Pull request by farisdurrani**
# Remove playground-frontend directory

**What user problem are we solving?**
Following #757 , we seek to deprecate the unnecessary /playground-frontend directory. All devs will need to manually move their files on their local branches:

https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/40067313/1029cb8d-6b48-43d0-bc94-9a743941490b

**What solution does this PR provide?**
Better navigation experience for the dev

**Testing Methodology**
Checked whether frontend and backend spun up using the normal commands

**Any other considerations**

### CODE REVIEW

**Review by karkir0003 — CHANGES_REQUESTED** [review]
did you test everything in the frontend? @farisdurrani

**Comment by farisdurrani** [comment]
> did you test everything in the frontend? @farisdurrani

As tested as it can be right now, calls to the backend seem functional

**Review by dwu359 — APPROVED** [review]

**Comment by farisdurrani** [comment]
@karkir0003 can you please approve this PR when you can? (it's set to Requesting Changes rn)

**Review by karkir0003 — APPROVED** [review]

**Comment by karkir0003** [comment]
approved @farisdurrani

**Comment by farisdurrani** [comment]
Will resolve conflicts later...

**Comment by karkir0003** [comment]
@farisdurrani is this file path naming good convention/practice? 

`frontend/playground-frontend/src/pages/train/[train_space_id].tsx`

**Comment by farisdurrani** [comment]
> @farisdurrani is this file path naming good convention/practice?
> 
> `frontend/playground-frontend/src/pages/train/[train_space_id].tsx`

Sorry Karthik just saw this, I'd say that's the standard convention, yes. Some may argue we should prepend the type of train model e,.g. tabular for more organization but that can also be a part of the trainspace id

**Comment by farisdurrani** [comment]
Closing this destructive PR while waiting for current PRs...

**Pull request closed without merging**
